/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface SwapperInterface extends utils.Interface {
  functions: {
    "swapBNBToBUSD(uint256,uint256)": FunctionFragment;
    "swapBUSDToBNB(uint256,uint256)": FunctionFragment;
    "transferBNB()": FunctionFragment;
    "transferBUSD()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "swapBNBToBUSD"
      | "swapBUSDToBNB"
      | "transferBNB"
      | "transferBUSD",
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "swapBNBToBUSD",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
  ): string;
  encodeFunctionData(
    functionFragment: "swapBUSDToBNB",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
  ): string;
  encodeFunctionData(
    functionFragment: "transferBNB",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "transferBUSD",
    values?: undefined,
  ): string;

  decodeFunctionResult(
    functionFragment: "swapBNBToBUSD",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapBUSDToBNB",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferBNB",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferBUSD",
    data: BytesLike,
  ): Result;

  events: {};
}

export interface Swapper extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SwapperInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>,
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>,
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    swapBNBToBUSD(
      amountBNB: PromiseOrValue<BigNumberish>,
      amountBUSD: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    swapBUSDToBNB(
      amountBUSD: PromiseOrValue<BigNumberish>,
      amountBNB: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    transferBNB(
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    transferBUSD(
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;
  };

  swapBNBToBUSD(
    amountBNB: PromiseOrValue<BigNumberish>,
    amountBUSD: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  swapBUSDToBNB(
    amountBUSD: PromiseOrValue<BigNumberish>,
    amountBNB: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  transferBNB(
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  transferBUSD(
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  callStatic: {
    swapBNBToBUSD(
      amountBNB: PromiseOrValue<BigNumberish>,
      amountBUSD: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<void>;

    swapBUSDToBNB(
      amountBUSD: PromiseOrValue<BigNumberish>,
      amountBNB: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<void>;

    transferBNB(overrides?: CallOverrides): Promise<void>;

    transferBUSD(overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    swapBNBToBUSD(
      amountBNB: PromiseOrValue<BigNumberish>,
      amountBUSD: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    swapBUSDToBNB(
      amountBUSD: PromiseOrValue<BigNumberish>,
      amountBNB: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    transferBNB(
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    transferBUSD(
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    swapBNBToBUSD(
      amountBNB: PromiseOrValue<BigNumberish>,
      amountBUSD: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    swapBUSDToBNB(
      amountBUSD: PromiseOrValue<BigNumberish>,
      amountBNB: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    transferBNB(
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    transferBUSD(
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;
  };
}
