/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Initializable",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.Initializable__factory>;
    getContractFactory(
      name: "Account",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.Account__factory>;
    getContractFactory(
      name: "Secp256r1",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.Secp256r1__factory>;
    getContractFactory(
      name: "UserOpLib",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.UserOpLib__factory>;
    getContractFactory(
      name: "Lock",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.Lock__factory>;

    getContractAt(
      name: "Initializable",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.Initializable>;
    getContractAt(
      name: "Account",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.Account>;
    getContractAt(
      name: "Secp256r1",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.Secp256r1>;
    getContractAt(
      name: "UserOpLib",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.UserOpLib>;
    getContractAt(
      name: "Lock",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.Lock>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer,
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer,
    ): Promise<ethers.Contract>;
  }
}
